### ISSUE TITLE
65 Errors 407 Warnings...

### ISSUE THREAD

**Issue by LYP951018** [vczh-libraries/GacUI#1]
用Visual Studio 2015 CTP 6直接打开的GacStudio.sln....难道是我打开方式不对。。。。
啊，好吧。。我改掉了new的宏定义。。这样就编译成功了，1407个Warning。。WX4.。。。

**Comment by wdhwg001** [comment]
说起来这个是开发用而那个gac的github是…发布用？为何不合并在一起，然后用release…

**Comment by vczh** [comment]
从codeplex搬过来有太多东西要做了，以后vczh/gac会删掉，然后在这边做release。

**Comment by vczh** [comment]
我一般都是开W3的，W4很多warning实在太没意思了，啊哈哈哈哈。
