### ISSUE TITLE
Windows 10 VS2015 生成文件过大

### ISSUE THREAD

**Issue by LER0ever** [vczh-libraries/GacUI#10]
环境：Windows 10 10586.104 64bit, Visual Studio 2015 Community.
在release里下载的0.7.8的zip，编译gaclib和gacliblite的静态链接库，结果一个**188588KB**，一个**82956KB**。
然后我试着编译了一下hello world 的cppxml demo，静态编译最终生成的可执行文件**15208KB**，都快赶上qt的静态大小了。。
_**不过运行是完全正常的**_
是不是我的环境配置的有问题？还是本来就这么大？因为听说

> 一个空白的GacLib程序静态链接crt只需要700k可执行文件大小。。。

![image](https://cloud.githubusercontent.com/assets/10568668/13394223/03c7ea3e-df22-11e5-97a8-4000e296d10e.png)
![image](https://cloud.githubusercontent.com/assets/10568668/13394509/da870e5a-df23-11e5-85a2-601e27256b3c.png)

**Comment by vczh** [comment]
1、pdb和lib本来就是超级大的，这是VS的问题
2、exe的话，如果你链接了GacUIReflection.cpp那就会很大，主要是因为这个文件夹进了一大堆为了支持反射而存在的字符串和代码，如果你尝试压缩他们的话会变的很小
3、最近正在做一个Workflow script转C++的功能，如果搞定了，那大部分程序都不需要GacUIReflection.cpp，就可以变回原本的2M大小了。
