### ISSUE TITLE
demo窗口界面的最大化图标错误

### ISSUE THREAD

**Issue by jshengst** [vczh-libraries/GacUI#102]
如题，

小窗模式下，显示的是缩小窗口的图标；大窗模式下，显示的是放大窗口的图标。

图标刚好弄反了

<img width="360" alt="Snipaste_2024-03-22_12-42-39" src="https://github.com/vczh-libraries/GacUI/assets/30409747/89099cd5-3f0d-491b-86e2-4bffa2ba0d0d">

题外话，GacUI是否支持svg这样的矢量图？在文档中没有看到相关的描述。

**Comment by pzhlkj6612** [comment]
FWIW: 我这里有一个写于 2018 年的程序，用的 [GacUI 0.9.5.0](https://github.com/vczh-libraries/Release/releases/tag/0.9.5.0)，那个最大化图标是正确的。

**Comment by vczh** [comment]
真的耶，这几天把他改了。

> GacUI是否支持svg这样的矢量图

没有做，不过如果你的平台是固定的，你可以用 `GuiGDIElement` 或者 `GuiDirect2DElement` ，在窗口刷新的时候会调用事件，然后给你底层的绘图设备，这样就可以拿去画svg了。

**Comment by vczh** [comment]
看了下代码发现我傻逼了，皮肤属性设置反了，把两个 `!=` 改成 `==` 就好了。不过hosted mode还有一点问题，我给修了之后把 commit 贴上来。如果你需要的话可以依样画葫芦做个patch，我不会马上直接更新release，毕竟其他功能写了一半。
