### ISSUE TITLE
inherited virtual base class 'vl::presentation::controls::GuiListControl::IItemProviderCallback'  has private destructor

### ISSUE THREAD

**Issue by leyafo** [vczh-libraries/GacUI#11]
我在 mac 下编译报这个错误，是怎么回事？   
IItemProviderCallback 这个 class 没有看到有 private destructor ？

**Comment by vczh** [comment]
@leyafo 修好了，刚update到Release repo里面去了

**Comment by vczh** [comment]
@leyafo 原因其实是Vlpp.h里面的一个继承忘记写public。话说VC++还真不会报这个错，而且这种错误其实也没有道理……override一个destructor又不是普通的那种override

**Comment by leyafo** [comment]
@vczh thanks.
