### ISSUE TITLE
PreferredMinSize NOT work when maximizing vertically

### ISSUE THREAD

**Issue by codehz** [vczh-libraries/GacUI#16]
DEMO "ContainersAndButtons"
Expected Behavier:
![image](https://cloud.githubusercontent.com/assets/13158903/19688431/4898c322-9afc-11e6-92a5-0befc2421d65.png)
Actual behavior:
![image](https://cloud.githubusercontent.com/assets/13158903/19688351/ed86bdfe-9afb-11e6-8a98-f93f4784d853.png)

**Comment by vczh** [comment]
No repro
