### ISSUE TITLE
scrollbar disappeared when selecting text in DocumentViewer(DEMO: Control Template)

### ISSUE THREAD

**Issue by codehz** [vczh-libraries/GacUI#17]
![BUG PREVIEW](http://i.giphy.com/l0MYKlXPZYSCSdNPG.gif)

**Comment by vczh** [comment]
I only see it disappear for 1 frame.

**Comment by vczh** [comment]
I only see it disappears for 1 frame.

**Comment by vczh** [comment]
@codehz fixed
