### ISSUE TITLE
DPI auto re-size and right-click support

### ISSUE THREAD

**Issue by wdhwg001** [vczh-libraries/GacUI#2]
It seems GacUI currently doesn't support DPI auto resize.
For example, the Controls.DatePicker.DateAndLocale demo:
![qq 20150406093747](https://cloud.githubusercontent.com/assets/8943519/6999587/2c5fde82-dc41-11e4-809e-27fa0e03f46f.png)

One other thing, the textbox and the scroll bar doesn't have a right-click menu. Yes I know it is Direct2D, but I think maybe it should still have the right-click support as a native widget does?

**Comment by vczh** [comment]
I do have a plan to add those right-click menus, but it will not be done before I developed the localization feature on text resources. Without that feature, I can add the menu, but people cannot translate to their favorite language if I don't speak that language.

Printing texts in GUI library is always that complex. If you look at the date control, you will find that names are well translated if you select different locales.

**Comment by wdhwg001** [comment]
But what about the DPI?
Perhaps the entire form need to be automatically re-sized in higher DPI, not only the font size.

**Comment by vczh** [comment]
For specific, the problem of the demo is that the window does not extend itself to fit the minimum size of the children. This is doable, but the demo is old so I don't update it. This is not a DPI problem. Currently the whole thing will get blur in high DPI.

1) The blur is about to change in the future.
2) I will rebuild all demos using XML resource, and they will become perfect again.

All this things will begin when my current task is done: Building the new document generator from XML comments in C++. It is almost done.

**Comment by wdhwg001** [comment]
Any updates to the right click menu?

**Comment by vczh** [comment]
@wdhwg001 currently no, just make one yourself, which is very easy in XML. I will begin to do this after [The TODO List](https://github.com/vczh-libraries/Release/blob/master/TODO.md) reaches "Locale awared text resource with str:// protocol".

**Comment by vczh** [comment]
Created another issue #37 to track this problem and close this for duplication. Now per-language text resource is supported for a few months, the right click menu should be able to created by XML without problems. But before 1.0 I will not add this feature into the library. This will be done in the future.
