### ISSUE TITLE
Create vcpkg port

### ISSUE THREAD

**Issue by sdcb** [vczh-libraries/GacUI#21]
Vcpkg is a tool to acquire and build C++ open source libraries on Windows.
With a port in vcpkg and we can just typing:
`vcpkg install gacui`
to install gacui, that would be cool.

Source here:
https://github.com/microsoft/vcpkg

Description here:
https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/

**Comment by vczh** [comment]
You are supposed to use the [source code here](https://github.com/vczh-libraries/Release/tree/master/Import). According to [the G4 section of this page](http://www.gaclib.net/#~/Tutorial), you only need 6 files to build GacUI. Obviously it doesn't require me to provide any more convenience. The GacUI repo is for development only.
