### ISSUE TITLE
将Qt Widget嵌入GacUI界面

### ISSUE THREAD

**Issue by wangwenx190** [vczh-libraries/GacUI#23]
轮子哥，请问如何将Qt Widget嵌入到GacUI的界面中啊？

**Comment by wangwenx190** [comment]
Qt Widget是可以转换成原生Win32窗口的，能不能把Win32窗口作为一种“控件”嵌入到GacUI中？

**Comment by vczh** [comment]
@wangwenx190 我没试过，不过理论上是没问题的。只要你不让别的控件遮挡你这个原生窗口的话就行。

**Comment by wangwenx190** [comment]
行，我试试，谢谢轮子哥

**Comment by car520120** [comment]
能给一下嵌入QT的例子吗？我想参考一下顺便学习一下！
