### ISSUE TITLE
GacUI能动态链接吗？

### ISSUE THREAD

**Issue by wangwenx190** [vczh-libraries/GacUI#24]
轮子哥，我把GacUI的Demo都编译过了，发现Demo都是静态链接GacUI的，能不能把GacUI编译成dll然后动态链接啊，感觉静态链接的话二进制文件比较大

**Comment by vczh** [comment]
才1M还大吗？想想仁王PC版，100G（逃

C++模板库是不可能动态链接的，而且你改成了dll也不能缩小总尺寸。

**Comment by wangwenx190** [comment]
明白了，谢轮子哥

**Comment by ngugc** [comment]
demo有1M的吗？最简单的cpp也2.4M。

**Comment by vczh** [comment]
@ngugc 以前是1M的，后来我把手写的皮肤干掉了，换成了现在临时的DarkSkin.xml，就变大了。你写一个比他简单的皮肤，就可以变小。

**Comment by ngugc** [comment]
@vczh , cpp那个demo也用了xml？

**Comment by vczh** [comment]
@ngugc Release repo的DarkSkin系列文件就是用GacUI项目里面的DarkSkin系列xml编译出来的。
