### ISSUE TITLE
请教XML写法

### ISSUE THREAD

**Issue by wangwenx190** [vczh-libraries/GacUI#25]
轮子哥，单纯看demo没法完整掌握GacUI的XML文件的写法，而GacUI也没有相关的文档，感觉入门挺困难的，没法快速上手，不知道轮子哥有没有开发能直接生成GacUI的XML文件的编辑器之类的工具？手写太麻烦了，而且还容易出错。没有类似工具的话，请问怎么才能较快的掌握GacUI的用法？连文档都没有实在痛苦啊（可别说http://www.gaclib.net/Document.html#~/这个是文档）。

**Comment by vczh** [comment]
还没写道那里。XML的名字基本跟C++的类名和函数名是对应的，你看看生成的代码马上就学会了。你可以看TODO.md来跟踪我的进度，等before 1.0勾完了，我就开始写编辑器。

**Comment by wangwenx190** [comment]
@vczh 好的，谢谢轮子哥了。

**Comment by DiskGetor** [comment]
xml 连接为bin？  这样不方面增加控件 在一个就是异步显示

**Comment by vczh** [comment]
@DiskGetor 改了xml之后重新生成就好了，不知道根增加控件有什么关系

**Comment by DiskGetor** [comment]
大师可以 单独加载xml方式吗？编译好慢 另外寻一个可视化xml设计器 我看好你这个工程

**Comment by vczh** [comment]
@DiskGetor 当然可以，只不过这样运行时就变得跟编译一样慢了（逃

**Comment by DiskGetor** [comment]
哪里的话，应该支持起来呃，你看在xml增加一个tabpage调整xy，这个过程用读取xml方式的时间和编译一次调整xy一次的时间相比，mfc我用创建控件的方式有过这个苦恼

设计器开发估计得很久才会有吧，设计器写xml

您这份工程，设计器+xml+推广应该会速度普及起来，我看目前0 error 0 warnning

**Comment by vczh** [comment]
@DiskGetor GacStudio最早明年

**Comment by vczh** [comment]
@DiskGetor 最近增加了resource xml之间互相依赖的功能，如果把一个大型resource拆开成几个小的，而每次只修改一个的话，编译时间就会下降。特此提醒。
