### ISSUE TITLE
DataGrid.exe  会崩溃卡死会造成电脑性能下降

### ISSUE THREAD

**Issue by stonedreamforest** [vczh-libraries/GacUI#31]
重现步骤：
![2018-05-03_13-43-06](https://user-images.githubusercontent.com/16742566/39561419-09255854-4ed8-11e8-88ea-ca080da8b397.gif)

**Comment by vczh** [comment]
我在做完手头的ribbon之后就来看看，不过这个步骤有点复杂，能不能简化一点？

**Comment by stonedreamforest** [comment]
在我演示的那几个位置左右键不停点击就好了

**Comment by vczh** [comment]
你要不再看看，之前修了几个menu跟list搞在一起导致crash的bug，可能这个就好了。不知道为什么我repro不了。

**Comment by stonedreamforest** [comment]
@vczh 依然崩溃
![WF2tIJatIO](https://user-images.githubusercontent.com/16742566/54474708-2434b500-4823-11e9-84b3-68a4d3b50fd7.gif)

**Comment by vczh** [comment]
@stonedreamforest 打个dump？

**Comment by stonedreamforest** [comment]
https://drive.google.com/file/d/1ELaOv3PFgQNhMLRoHqG0eHpTkx0gGcAJ/view?usp=sharing

**Comment by vczh** [comment]
@stonedreamforest 你用的是release最新的release还是最新的代码还是哪个版本的代码？我也编译一个好用这个dump

**Comment by stonedreamforest** [comment]
> @stonedreamforest你用的是发布最新的版本还是最新的代码还是哪个版本的代码？我也编译一个好用这个转储
最新版：
https://github.com/vczh-libraries/GacUI/archive/master.zip
貌似提供了pdb 用windbg打开了应该可以分析

**Comment by stonedreamforest** [comment]
> @stonedreamforest你用的是发布最新的版本还是最新的代码还是哪个版本的代码？我也编译一个好用

这个转储
最新版：
https://github.com/vczh-libraries/GacUI/archive/master.zip
貌似提供了pdb 用windbg打开了应该可以分析

**Comment by vczh** [comment]
@stonedreamforest 我来看看

**Comment by stonedreamforest** [comment]
@vczh  还卡死啊 😂

![pAlpQ868M7](https://user-images.githubusercontent.com/16742566/80131445-d6b17c80-85cc-11ea-81ec-eda089afa2a0.gif)

准备用这个gui开发一个工具来着。。。

**Comment by vczh** [comment]
@stonedreamforest 一直没机会看，还在做文档的事情（逃

**Comment by vczh** [comment]
写文档好忙啊，要是有个人帮我做就好了（逃

vczh-libraries.github.io 有了巨大的变化

**Comment by vczh** [comment]
修了，发现原来是切换DataGrid 样式的时候，忘记detach一个事件
