### ISSUE TITLE
released静态库过大

### ISSUE THREAD

**Issue by yunhai2009** [vczh-libraries/GacUI#32]
您好

环境：win7 32位，VS2017 
问题1：用Windows SDK 10.0.16299.0编译会有使用SDK头文件错误的error。
问题2：换用Windows SDK 10.0.17134.0编译可以通过但VS2017编译缓慢且电脑比较卡，编译出来的静态库GacUI.lib--336M GacUIComplete.lib--104M GacUILite.lib--99.4M

**Comment by vczh** [comment]
那个Lib项目只是demo的一部分。如果你觉得Lib太大你的编译器版本搞不定的话，你有两个办法：
- 直接把代码包含进vcxproj，这样就不需要产生lib文件。
- 依赖Lib的项目在Linker->General->Use Library Dependency Inputs选Yes，这样链接的时候会直接拿Lib项目的obj文件来链接，不会使用到lib文件，我猜头文件错误就不会发生。

VC++的lib就是这样的了，我也没办法。反正HelloWorld的Cpp.exe也只有3M，结果足够好。

"by design"
