### ISSUE TITLE
稍微看了下，有一些疑惑

### ISSUE THREAD

**Issue by jadedrip** [vczh-libraries/GacUI#35]
我稍微看了一下源码，并没有深入，但发现有很多重新发明的轮子，比如 FileStream, Array 这样的东东，想知道作者这样设计的意图是什么？为什么不使用标准库呢？
Resource.xml 里是完全新的语法，而且不知道里面的脚本到底是啥语言？真希望能自定义脚本引擎，用上 javascript, lua 之类熟悉的东西。
现在感觉这个库的学习成本有点高啊，怕怕。

**Comment by vczh** [comment]
你可以关心一下Release repo的todo.md，现在文档还在写，写完你就明白了。

简单来说，这个库的基础部分在我还没大学毕业的时候就开始了，那个时候的标准库就是一坨屎。写到今天标准库仍然还有一些东西没有完成，譬如说带高级capture的regex，譬如说localization，譬如说linq（还在标准里没拉出来）。所以这就是为什么我干脆重新来了一遍。

脚本的话，你可以理解为就是把C++改成了容易理解的样子，骨子里还是引用计数，基本观点跟COM差不多。脚本经过GacGen.exe编译之后完全被重写成了C++，可以摆脱所有对反射的依赖，直接用javascript和lua没办法做到这一点。当然你愿意自己写一个javascript到C++的编译器的话，随时可以来PR（逃

**Comment by jadedrip** [comment]
了解了，不过现在是 C++ 17 的时代了，标准库也稳定了，建议还是尽量用标准库吧，一个新库降低学习成本还是很重要的，这样可以让更多人来使用。
现在就等教程了，追）

**Comment by FirstLoveLife** [comment]
> 标准库也稳定了

Nope. Many c++11 stuffs have been deprecated in 17/20

**Comment by jxd134** [comment]
@FirstLoveLife 
有哪些c++特性在17/20废弃了呢。
就我所知，有std::shared_ptr的接口

**Comment by FirstLoveLife** [comment]
P0174R2

**Comment by vczh** [comment]
降低学习成本是好的，但是我并不相信使用标准库就能降低学习成本，因为这么多年来标准库就是没有人用的。

**Comment by jadedrip** [comment]
哦，我说的是两件事，用标准库的意思，是减少重复的轮子，以便集中精力做更重要的东东。
第二件事是建议用 lua, javascript 之类的知名脚本，而不是重新做一个，以降低别人的学习成本。
其实包括你的 xml 定义也是自己重新做的吧，在没有成熟编辑器的情况下，学习成本也会很高。

也就是个建议而已。

**Comment by vczh** [comment]
@jadedrip 还行，反正我也没找到什么靠谱的js和lua到C++的编译器，而且这些语言的逻辑是自带垃圾收集的，不合适。我需要的是一门没有垃圾收集的脚本。一开始我认为应该是Basic，但是Basic也是太多分支了。

**Comment by sekkit** [comment]
本来想提一个python/C# binding的issue，但是要求把脚本翻译成c++。为什么不仅仅导出api给脚本调用，用户的业务逻辑可以在纯脚本层 这样更符合大众的习惯。
提这个问题可能理解不到位。
目前一些支持脚本的小gui库挺多人用，且支持热更新

**Comment by vczh** [comment]
@sekkit 一般来说，脚本做的GUI程序不需要有酷炫的特效，因此他们不需要使用C++代码来操作具体的控件，只要结合MVVM、data binding和少量的xml里面的脚本代码就可以了。我建议如下操作：
- 还是用原来的办法用XML写GUI
- 把XML编译成C++
- 用脚本来实现view model，然后反向bind进这个C++项目里。这个以后可以写一些codegen来做，你有兴趣也可以试试看（逃
- 编译一下就得到用XML、workflow和你喜爱的脚本语言写的GUI程序了

**Comment by MouriNaruto** [comment]
既然提到 Basic，不知道 @vczh 是否用过 FreeBasic
近十年前，我还是初中生的时候，听说了这个有 include 且自举的 Basic 工具集
