### ISSUE TITLE
使用的编译问题

### ISSUE THREAD

**Issue by sekkit** [vczh-libraries/GacUI#38]
有个小客户端项目需要用C++写，想了想就下载了GacUI，但是用Visual Studio 2017打开后，编译提示：
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1001	An internal error has occurred in the compiler.	GacStudio	C:\Users\sekkit\Downloads\GacUI-master\Tools\GacStudio\GacStudio\c1xx	1	

是要用Win7才可以吗，本人是Win10 1803. 如果实在不行就用小duilib的库了，其实那种也很方便。

PS: 本人最想要的是可以选择Win2k，WinXP的luna和Win7的aeroglass主题风格，这些能不能以后内置到库里面去。Win8/10的风格实在难以接受。

**Comment by vczh** [comment]
这个项目是没用的，我也不提供工程文件，请看本repo的readme，然后去 https://github.com/vczh-libraries/release 获取最新版本。
