### ISSUE TITLE
对Alt键的处理问题

### ISSUE THREAD

**Issue by variousvirgil** [vczh-libraries/GacUI#4]
如果窗口使用了Template的效果但是没有Tab就像是Demo里面Template.Window.CustomizedBorder一样时，直接按下Alt键会导致崩溃；如果有使用Tab比如Demo里面Persistant.LoadFromXml.ControlTemplate则会在Tab上显示数字标号(不过现在好像还不能当快捷键用)，不会崩溃。

----------------Edit---------------
此处描述不当，请见之后回复

**Comment by vczh** [comment]
什么叫Template的效果？

**Comment by variousvirgil** [comment]
是我用语不太准确，比如Demo里面Template.Window.CustomizedBorder在主界面按下alt键就会崩溃。貌似使用了自定义的Window Style而且AltAction是空的话按下Alt键就会当在CreateAltTitles里面。

**Comment by vczh** [comment]
现在正在搞GacUI的新的HTML文档。等我把事情做完了就来debug一下。

**Comment by vczh** [comment]
@variousvirgil 修好了。其实不是因为CustomizedBorder，而是ComboBox的问题。他继承了MenuButton，总是会引发alt，然而ComboBox是不支持alt的，而且也没给他设置alt属性，加上恰好窗口上只有一个ComboBox，结果就让显示的小黄标签的长度为0，然后就炸了。

**Comment by variousvirgil** [comment]
谢谢！

**Comment by vczh** [comment]
@variousvirgil 不过要等他上release还需要一小段时间。当Release repo发表了下一个release的时候，这个bug就没有了。
