### ISSUE TITLE
Microsoft Reference Source License seems block any modifications to this project

### ISSUE THREAD

**Issue by yinyue200** [vczh-libraries/GacUI#43]
"Reference use" means use of the software within your company as a reference, in read only form,

I think it better to disable pull requests or change license

**Comment by vczh** [comment]
You are supposed to use [this repo](https://github.com/vczh-libraries/Release). According to the license, you have two way to modify this project:

- the `Release` repo allow you to modify, and you have to license me your modification appropriately.
  - Please note that extending GacUI (e.g. adding controls, adding skins) is not modify, but porting to another platform is.
- make pull request to the `GacUI` repo. I don't think "Reference use" disallow you to join this project, it just block you from releasing your fork to the `GacUI` repo.

Please contact me if you have further concern.
