### ISSUE TITLE
Glitch in layout system

### ISSUE THREAD

**Issue by codehz** [vczh-libraries/GacUI#44]
录制帧率不高，不过足够表现问题了，实际情形是鼠标移动时每一帧都在抖动。。
猜测 为 HiDPI 支持的问题，缩放为125%时发生
![bug](https://user-images.githubusercontent.com/13158903/68083998-af25f680-fe6a-11e9-88e9-9b4a6eec1773.gif)

**Comment by vczh** [comment]
是不是100%就不发生？如果是的话我得换我的笔记本来debug才能看见。

**Comment by codehz** [comment]
没错，100%就没有这个问题了（当然缩放不跟手应该是正常情况（）），另外其实这个问题在所有方向上拖动都有体现，只是左上角看起来最明显

**Comment by codehz** [comment]
另外额外注明一下，windows 10的两种缩放模式（就是一个直接调整，一个改高级缩放设置里的比例）下都有这个故障，应该不是系统设置的问题

**Comment by codehz** [comment]
详细测试表明，问题触发有几个条件
1. 启用非整数缩放（测试了125/150
2. 复杂布局（总之Hello world没出问题）
3. 要调整到某个最小宽度/高度范围才会出问题（但是我没找到设置最小宽度的位置）

minor bug:
Layout > Responsive测试中
第一个测试当文本编辑使得宽度变宽超出范围的时候，窗体高度和宽度同时被扩张（我没看出这里扩张高度的意义在哪里，还是可以手动拉回去的。

**Comment by vczh** [comment]
200就没有问题？

我觉得这个可能跟我的排版算法有关，我不是每一帧都求解出全部约束的，如果表格嵌套的话一般都要两三帧，然后让这些约束自然的传播到最上面。需要进一步debug来确认。

**Comment by codehz** [comment]
200的问题不明显，和100的感觉差不多。。
起码没有跳变回去的感觉，在左上角改变大小的时候，只是内容被裁剪了几帧，并不会左右横跳。（关键右侧横跳还好，左侧横跳意味着窗口位置也在乱变了

**Comment by vczh** [comment]
可能是移动的时候没写好，因为WM_SIZE和WM_MOVE是分开发给我的，这个就特别蛋疼。

**Comment by vczh** [comment]
Duplicated with #66
