### ISSUE TITLE
textbox selection issue

### ISSUE THREAD

**Issue by codehz** [vczh-libraries/GacUI#46]
![image](https://user-images.githubusercontent.com/13158903/68084107-3b84e900-fe6c-11e9-9db9-315819ce650a.png)
如图所示，所选文字背景颜色被奇怪的分割了

**Comment by vczh** [comment]
等我最近的Document repo搞完我来看看

**Comment by vczh** [comment]
这个也跟scaling有关吗，是不是在100%下看不到？

**Comment by codehz** [comment]
测试了一次，是这样的，100%的时候没有问题

**Comment by vczh** [comment]
https://github.com/vczh-libraries/GacUI/commit/daa616ccdfc1cc6600932c616921c8c800300ed9

**Comment by vczh** [comment]
本来选择文字的背景颜色是不透明的，但是因为非整数的text scaling会导致边缘反锯齿，反锯齿的结果带有alpha通道，叠加在一起就不好看了。现在改成一行一行刷。
