### ISSUE TITLE
技术交流：请教轮子哥，如何使无边框窗口响应窗口管理器

### ISSUE THREAD

**Issue by wangwenx190** [vczh-libraries/GacUI#47]
轮子哥，您好。我最近在尝试使用Qt制作无边框的窗口，我用`setWindowFlags(Qt::Window | Qt::FramelessWindowHint)`去掉了窗口边框，并且我使用Qt的事件过滤器截取了Windows事件，我在`WM_NCHITTEST`事件里处理了鼠标指针的变化以及实现了窗口拖动。我用`DwmExtendFrameIntoClientArea(hwnd, {-1,-1,-1,-1})`带回了窗口的边框阴影，可是我发现我的无边框窗口无法响应Win+←、Win+→、Win+↑以及Win+↓，也无法在拖动到桌面顶端的时候自动最大化，感觉像是无法响应“窗口管理器”（如果有这么一个东西的话）。GacUI也是自己搞的边框，用起来跟原生的边框一模一样，请问您是调用了什么API，来实现这种与“窗口管理器”的对接？

**Comment by wangwenx190** [comment]
已经自行解决了，抱歉打扰轮子哥了。

**Comment by vczh** [comment]
> 已经自行解决了，抱歉打扰轮子哥了。

具体我也记不清楚到底是为什么了，但是我记得我在设置边框的时候，保留了“窗口有边框”的这个特性，然后Windows就会帮我做。我不是自己处理的。

**Comment by wangwenx190** [comment]
> 
> 
> > 已经自行解决了，抱歉打扰轮子哥了。
> 
> 具体我也记不清楚到底是为什么了，但是我记得我在设置边框的时候，保留了“窗口有边框”的这个特性，然后Windows就会帮我做。我不是自己处理的。

是的，我研究了一下，发现只有保留窗口边框才能和系统进行交互，要使用系统提供的各种特性就不能真的把边框去掉，我提到的那些窗口事件是没法用Win32 API模拟出来的。大家通常的做法就是保留边框，然后在`nativeEvent`里去掉标题栏，导致看起来好像没有边框一样，实际上只是隐藏掉了，因此各种边框的功能都还保留着。如果真的把边框完全去掉了，只有8方向拉伸和窗口阴影是能重新做出来的，其他特性很难手动实现，我也没见过类似的项目。

**Comment by vczh** [comment]
@wangwenx190 我觉得这也是合理的，每个版本的Windows的做法都不一样，如果你自己干，就没法在未来的Windows下完美运行。
