### ISSUE TITLE
可不可以提供dll文件

### ISSUE THREAD

**Issue by xland** [vczh-libraries/GacUI#5]
可不可以提供dll文件和c语言的头文件~
这样对于只使用C开发的人来说就方便多啦~

我看到SDL2也是这么干的

**Comment by variousvirgil** [comment]
见www.cppblog.com/vczh/archive/2011/11/23/160835.html

**Comment by xland** [comment]
3、
存在dll，并且使用比模板丑陋的方法来将本来使用模板做接口的功能暴露出来。


强烈推荐第三种方法！
对于c语言、nim语言、rust语言、go语言的开发者，可以简单的封装就能使用gac的强大图形化功能，这种方法是最赞的！

**Comment by xland** [comment]
这种投票办法，非常不公平~

来作者博客投票的人都是C++使用者，

C语言、nim语言、rust语言、go语言的用户要想使用gaclib该怎么办啊，

轮子兄行行好，听听我们的意见.

**Comment by vczh** [comment]
现在已经不行了

-----Original Message-----

**Comment by vczh** [comment]
@xland 我的C++有反射，你们可以自己bind进去，详情看Workflow脚本和https://github.com/vczh-libraries/GacUI/tree/master/Source/Reflection/TypeDescriptors 。然后你们自己build成dll。
