### ISSUE TITLE
Table control 能否实现aggregatable接口

### ISSUE THREAD

**Issue by roodkcab** [vczh-libraries/GacUI#50]
想把多个table界面写到不同的xml里去，发现必须要在table上套一层实现了aggregatable的控件(custom/tabpage)，which只能
`
<Instance name="">
  <Instance ref.Class="LoginWindow">
    <CustomControl>
      <Table>
      </Table>
...
`
不想把多个界面的Workflow都写在一个Resource文件里

**Comment by vczh** [comment]
目前只有Window、CustomControl和TabPage可以被继承，其他的我都建议放到CustomControl里面。
