### ISSUE TITLE
mvvm转场动画如何实现？

### ISSUE THREAD

**Issue by roodkcab** [vczh-libraries/GacUI#51]
同一个window下的两个界面visbile-bind到一个bool上之后，界面马上就切换了，想做一个转场动画，要怎么实现呢？

**Comment by vczh** [comment]
不知道你具体遇到了什么问题，但是原则上，既然是动画，那当然你要自己去算动画的运行过程了，包括这些控件的位置什么的。目前的GacUI只提供了动画的基础部件，没有这些辅助的功能，要自己写公式实现。

**Comment by roodkcab** [comment]
嗯，之前没看到animation的例子，我去写一个转场的东西出来，稍后贴到这里。
