### ISSUE TITLE
Object 序列化

### ISSUE THREAD

**Issue by roodkcab** [vczh-libraries/GacUI#53]
如果可以直接将Object直接序列化到文件并可以反序列化的话，就可以省去存储的代码了。更进一步的话workflow定义出来的就是orm的接口，这样GacUI本身就是数据库的一层皮，还能跨平台，简直就是福音。

**Comment by vczh** [comment]
你具体想要怎么被序列化？做一个序列化其实需要很多内容的，譬如怎么变成JSON，怎么变成XML，怎么变成其他格式，甚至是二进制文件什么的，东西还挺多的。

**Comment by roodkcab** [comment]
比如对一个ViewModel支持一个ISerializable的接口，然后自己实现serialize函数

json、xml还是binary或者是xml里cdata的binary都可以自定义archive，然后把常见的一些数据类型比如IValueList、WString什么的实现serilaize之后，在自定义的serialize中只要挨个指定要序列化的字段就好。

类似这样？
```	
template<class BinaryArchive>
void serialize(BinaryArchive& archive)
{
	archive(CEREAL_NVP(website), CEREAL_NVP(username), CEREAL_NVP(password));
}
};
```

**Comment by vczh** [comment]
https://github.com/vczh-libraries/Workflow/blob/master/Source/Runtime/WfRuntimeAssembly.cpp

其实也不是一点都没有，这个文件里面就有一个完整的例子，不过因为做的不是很general，所以我没写进文档里。这个是专门序列化成二进制文件的。
