### ISSUE TITLE
关于文本输入

### ISSUE THREAD

**Issue by mingy532** [vczh-libraries/GacUI#54]
会加入类似[这里](https://www.scintilla.org/SciTEDownload.html)文本输入的效果吗。
看了下notepad++的源码，发现使用了Scintilla，然后看了这个[例子](https://github.com/vczh-libraries/Release/tree/master/Tutorial/GacUI_Controls/TextEditor)，发现合成窗口是在光标下方出现的。
想问下如果要实现SciTE或者notepad++里的合成窗口直接跟在当前输入行后面要怎么做。以及，Gaclib会支持这个吗。

**Comment by mingy532** [comment]
我的意思是，是否会实现[这样](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/winui/input/ime/fullime)的效果。
//顺便问下，为什么这个例子不会弹出汉语候选窗口。而[另一个](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/winui/input/ime/halfime)在打开选项之后就可以了。
以及，“Windows-classic-sample”系列值得一看吗，是不是有更modern的值得去看了。

**Comment by vczh** [comment]
这个是要做的，不过不重要，所以先做别的。

总的来说，如果你要跟输入法互动，你要用API主动去通知输入法的，不是什么都不管他自己就有的。

**Comment by mingy532** [comment]
好吧，期待。
