### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [vczh-libraries/GacUI#6]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [GuiApplication](https://github.com/vczh-libraries/GacUI/blob/6ca85dcfb8d22a1755736e0ac6a6ebf151675fbe/Source/Controls/GuiApplication.cpp#L73)
- [GuiGraphicsHost](https://github.com/vczh-libraries/GacUI/blob/6ca85dcfb8d22a1755736e0ac6a6ebf151675fbe/Source/GraphicsElement/GuiGraphicsHost.cpp#L853)
- [TextLine::Finalize](https://github.com/vczh-libraries/GacUI/blob/6ca85dcfb8d22a1755736e0ac6a6ebf151675fbe/Source/GraphicsElement/GuiGraphicsTextElement.cpp#L55)

**Comment by vczh** [comment]
@elfring sounds reasonable. I will fix them when I touch this project the next time if I still remember. I am making a new website.
