### ISSUE TITLE
可以把工程管理换成国产的吗？

### ISSUE THREAD

**Issue by car520120** [vczh-libraries/GacUI#65]
xmake 这个工具，方便编译，也支持跨平台的

**Comment by vczh** [comment]
linux下用makefile，mac的代码在iGac，我觉得都很好，没必要换。

**Comment by car520120** [comment]
能帮忙支持一下吗？大神，我主要是学习使用的...你也希望用的人多吧！

**Comment by car520120** [comment]
大神，你的底层是每一个平台都写一个版本的吗？会封装和 bgfx 类似的吗？

**Comment by vczh** [comment]
macOS在iGac基本能用了，Linux在XGac还不能用，到时候还会支持UWP和浏览器等等，底层的部分各自重写，高层的大部分代码都不需要改。

**Comment by mangosroom** [comment]
我写了一点CMakeLists.txt，提供了GacUI-Realease的CMake管理，支持导入导出。[https://github.com/mangosroom/GacUI-CMake-support](https://github.com/mangosroom/GacUI-CMake-support)

**Comment by vczh** [comment]
@mangosroom 牛逼啊，我在release的readme提一下。

**Comment by mangosroom** [comment]
> @mangosroom 牛逼啊，我在release的readme提一下。

为GacUI的生态尽一点点绵薄之力，好东西就应该让更多开发者使用起来。后续其他平台的的代码合并到Release后我也会继续更新CMake的支持。
