### ISSUE TITLE
WindowsController::GetExecutablePath 分配内存过大

### ISSUE THREAD

**Issue by LYP951018** [vczh-libraries/GacUI#7]
[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)
>The Windows API has many functions that also have Unicode versions to permit an extended-length >path for a maximum total path length of 32,767 characters.

而源代码中分配了 65536 characters：
```cpp
WString GetExecutablePath()
{
		Array<wchar_t> buffer(65536);
		GetModuleFileName(NULL, &buffer[0], (DWORD)buffer.Count());
		return &buffer[0];
}
```
而且有个小建议就是，可以一点一点试大小（[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683197%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)评论里面的。。），毕竟长路径情况太少了。。。

**Comment by vczh** [comment]
反正是堆上的，没什么关系。如果你一定要变小的话，要不你改成32768然后pull request上来（逃
