### ISSUE TITLE
关于重型UI的问题咨询

### ISSUE THREAD

**Issue by libbylg** [vczh-libraries/GacUI#70]
我们这边是做工业软件的。目前有一些界面比较特殊：就是界面上图元特别多。比如，载入一个多层的版图，一下子就要显示几万的图元。还要在这些图元上支持缩放、数据标注（颜色、线性、操作状态、附加的标签等等）、响应用户的点击选取等操作。这个时候，我们发现，我们的UI框架就跪了。最早是一个一个控件往上堆，内存大，视图卡，CPU高。后来，换其他支持大量图元的框架，内存稍微好点，缩放还是卡，操作响应还是慢。databind这种不敢用，因为数据放两份内存会更大，而且担心动态加标注会很不方便。

这些问题我们有过一些分析，主要问题集中在下面：
1、需要呈现数据太大，传统的界面上往往要存部分业务的数据（比如，坐标信息我们是自带的，但是框架要自己管，我们还要做个映射），导致内存资源消耗较大。
2、由于ui要支持缩放，现有的ui框架几乎都清一色地需要将全部图元加入管理器才能做到，这既导致内存开销大，又会触发底层管理机制管理超大量图元时低效的问题。
3、由于图元多，遇到缩放等操作时，要绘制的东西很多。由于跨层不遮盖也需要显示等诉求，导致页面刷新时会多层绘制，绘制过程页面脏、花、慢。

请教下，像这种场景 gacui 框架是否有办法解决？

**Comment by vczh** [comment]
GacUI也有类似的功能，不过总体上是用来做UI排版的，通过两个方面来解决：
1. 如果是列表的话，只有看得见的部分会在内存里创造图元，滚到哪里就做到哪里，滚进来的就创建，滚出去的就删除。
2. 图元本身也只是普通的数据结构，看不见的部分最终也不会调用API渲染，不过图元多起来的话总归会浪费一些计算资源。

不过GacUI的图元终归是为了渲染控件做的，所以只有简单的几何图形、填充颜色、图片和文字等等。如果你需要其他的图元，得自己画。我会开放Direct2D或者GDI的API，可以让自己掌管一部分的渲染过程。

但是我不知道你的图元到底是为了什么，如果是像PowerPoint或者Visio那样的可交互的复杂图形，但是没有控件那么复杂的交互过程的话（譬如说动态编辑文字啊菜单啊什么的），我建议你还是像开发游戏那样，只要给你的一大片图元做场景管理（简单来说如四叉树），那你可以在渲染和交互的时候，如果看得见的部分只是一小部分，那么就可以在早期剔除掉大量的无用计算。缺点就是渲染和databinding都得自己实现了。这不仅仅是GacUI，任何UI框架上可能都得这么做。

如果你的图元可以用列表或者表格来排版的话，那GacUI就有现成的。

**Comment by libbylg** [comment]
非常感谢您的答复！

您提到的虚拟列表这种『只负责绘图和交互控制，而列表自身不存大量数据』的机制确实跟我们的诉求很匹配。而差异点刚好也不是列表简单的、交互受限的数据呈现形式。CAD中的版图数据呈现形式更像地图这种形式，确实就是几何图形（比地图形状简单，但是线条数量更多）、填充、以及文字标注。图形之间的相对位置是固定的，没有排版要求，并不能像PPT那样随意编辑。其实版图的原始布局布线一般是自动生成，然后设计人员做微调。但设计工具我还没接触过，目前主要还是查看和附加标注的诉求。

现在具备一定完成度的UI的，还具备可移植性的框架真没几个了。我确实分析过几个UI框架，发现基本上面向的都是一个页面上只展示少量图元的场景。Qt的GraphicView框架很接近我们的期望。我们有个团队曾经遇到类似的问题，改一版。但他们场景没我们的大，他们也不建议拿他们的代码用。也是建议我们从OpenGL重写一个。

我感觉我们好想就只有自己从OpenGL这一层开始做，这一条路了。

感谢您的回复，让我明确了方向！

非常感谢！也祝您的GacUI框架能前途无量！

**Comment by vczh** [comment]
看起来像是绘制电路图那样的东西，的确需要自己来。绘图的加速和交互（譬如说最简单的，鼠标点击一下，你的程序得知道点中了什么东西）都可以用四叉树来加速。如果你的图形的分布比较均匀的话，四叉树还是相对节省内存的选择。图形改动了你只要重建一次四叉树就好了，鉴于不用频繁编辑，所以我觉得这样应该够了。
