### ISSUE TITLE
请问Gac采用什么开源协议呢？

### ISSUE THREAD

**Issue by wphu** [vczh-libraries/GacUI#71]
请问Gac采用什么开源协议呢？

**Comment by pzhlkj6612** [comment]
你好。

在 [README.md](https://github.com/vczh-libraries/GacUI/blob/b154dd02607f9b420cd59fc0970681d99697dcde/README.md) 中有：

> **Read the [LICENSE](https://github.com/vczh-libraries/GacUI/blob/master/LICENSE.md) first.**

在 [LICENSE](https://github.com/vczh-libraries/GacUI/blob/b154dd02607f9b420cd59fc0970681d99697dcde/LICENSE.md) 中有：

> See https://github.com/vczh-libraries/License/blob/master/README.md for the detail.

[vczh-libraries/License](https://github.com/vczh-libraries/License) 仓库中的 [README.md](https://github.com/vczh-libraries/License/blob/f28575df309aeb0ad2ab2452ff087b223989cacd/README.md) 即为你需要的内容。

**Comment by wphu** [comment]
明白了，多谢了。
