### ISSUE TITLE
尝试添加skia

### ISSUE THREAD

**Issue by bizehao** [vczh-libraries/GacUI#72]
轮子哥，我想添加个skia渲染，能大体给我说下要动那些文件吗

**Comment by vczh** [comment]
你可以参考Direct2D和GDI的部分。调试的时候可以在这个repo里面做，不过到时候还得考虑怎么跟release repo里面的代码互动，除非你知道怎么build出 GacUI/release 下面的内容。

https://github.com/vczh-libraries/GacUI/tree/master/Source/NativeWindow/Windows 这里是初始化程序框架，以及给渲染代码提供API的地方。

https://github.com/vczh-libraries/GacUI/tree/master/Source/GraphicsElement 这里是实现具体渲染图形的细节的地方。

依葫芦画瓢就可以。

**Comment by bizehao** [comment]
好的，我试试看

**Comment by bizehao** [comment]
谢谢轮子哥，好好研究下你的代码
