### ISSUE TITLE
列表 listview（bug: 滚动条的滑块应该大一点）

### ISSUE THREAD

**Issue by bizehao** [vczh-libraries/GacUI#73]
列表数量一多，鼠标在不同项之间悬浮，悬浮效果感觉有点慢，卡的那种感觉

**Comment by vczh** [comment]
你试试release？debug因为我开了内存泄漏跟踪，很容易就会变得比较卡。

**Comment by bizehao** [comment]
> 你试试release？debug因为我开了内存泄漏跟踪，很容易就会变得比较卡。

确实，用release很丝滑。还有个问题，就是列表数量太多的时候，列表的滑块会变得非常小，很难鼠标拖动，我查找api，发现滑块没有设置最小高度的，希望能加一个。

**Comment by vczh** [comment]
GacUI认为控件不应该管太多，跟功能无关的东西都是做在皮肤里面的。默认的皮肤在这里：
https://github.com/vczh-libraries/GacUI/blob/master/Source/Skins/DarkSkin/Template_Scroll.xml#L138
https://github.com/vczh-libraries/GacUI/blob/master/Source/Skins/DarkSkin/Template_Scroll.xml#L181

给`<PartialView>`加上`PrefferedMinSize`属性就行了，跟同一个文件下面tracker的皮肤一样。H滚动条就加上非零x，V滚动条就加上非零y。

编译的话就调用[GacBuild.ps1](https://github.com/vczh-libraries/Release/blob/master/Tools/GacBuild.ps1)去跑[Resource.xml](https://github.com/vczh-libraries/GacUI/blob/master/Source/Skins/DarkSkin/Resource.xml)，你会看到Source目录下的C++文件改了。

再调用[Codepack.exe](https://github.com/vczh-libraries/VlppParser2/tree/master/Tools/CodePack/CodePack)去跑[CodegenConfig.xml](https://github.com/vczh-libraries/GacUI/blob/master/Release/CodegenConfig.xml)，你会发现GacUI/Release下面几个C++文件改了。

你把改了的文件替换掉Resource repo的几个就好了，如无意外的话应该只有`DarkSkin.cpp`一个文件有改动。

**Comment by bizehao** [comment]
ok 非常感谢

**Comment by vczh** [comment]
我估摸着这是Direct2D的问题，在Windows 10的第一版及所有旧版Windows都不要用Direct2D的64位。我先close了，有什么新发现的话再reopen。

**Comment by vczh** [comment]
后来我发现数据极端多的话滑块甚至会消失，确实应该至少hardcode一个最小宽度。

**Comment by bizehao** [comment]
是啊，现在主要缺少个xml标签提示的编辑器，我通过gacui提供的反射生成的xsl应用到xml里，用vscode编辑时，还是很不方便，提示不太好

**Comment by vczh** [comment]
没想到github还能因为我在commit上说修掉了这个bug就把它close了。不过代码还在这个repo里没进release，很快下个版本号就出来了。
