### ISSUE TITLE
x64位模式下崩溃问题

### ISSUE THREAD

**Issue by bizehao** [vczh-libraries/GacUI#75]
32位模式下正常，64位下会崩溃.
在有动画的情况下尤为明显，一会就崩了,

我经过排查，感觉像是画刷资源共用的问题,但是32位下没事,就解释不同了。
我把颜色随机改变，资源缓冲区里的每一个画刷都是唯一的，就不会崩溃。或者说
![image](https://user-images.githubusercontent.com/33247680/170817976-c729830c-b20e-4840-a5c5-b4b9858b310f.png)
这样,也不会崩溃。

这是堆栈信息：
 	KernelBase.dll!00007fff8a0dd532()	未知
 	d2d1debug3.dll!DebugLayer::OutputGlobalErrorMessage(unsigned int,...)	未知
 	d2d1debug3.dll!ResourceSDK::CResourceUsageMgr<struct IUnknown *,struct ResourceSDK::NoExemptionPolicy,struct ResourceSDK::DefaultNewAndDeleteOperators,struct ResourceSDK::RentalThreadedResourceUsagePolicy,struct Reporter,class DebugTracker,class ResourceSDK::CDictionary<struct IUnknown *,class DebugTracker,struct ResourceSDK::DefaultNewAndDeleteOperators> >::ClosedHandleCheck(struct IUnknown *)	未知
 	d2d1debug3.dll!DebugLayer::TestResourcePreApi(struct IUnknown const *,struct DebugTracker::Storage const *,bool)	未知
 	d2d1debug3.dll!DebugRenderTargetGenerated<struct ID2D1BitmapRenderTarget>::FillEllipse(struct D2D1_ELLIPSE const *,struct ID2D1Brush *)	未知
>	MyGacUiTest.exe!ID2D1RenderTarget::FillEllipse(const D2D1_ELLIPSE & ellipse, ID2D1Brush * brush) 行 3137	C++
 	MyGacUiTest.exe!vl::presentation::elements_windows_d2d::GuiSolidBackgroundElementRenderer::Render(vl::presentation::Rect_<__int64> bounds) 行 392	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 309	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsComposition::Render(vl::presentation::Size_<__int64> offset) 行 325	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsHost::Render(bool forceUpdate) 行 637	C++
 	MyGacUiTest.exe!vl::presentation::compositions::GuiGraphicsHost::GlobalTimer() 行 560	C++
 	MyGacUiTest.exe!vl::presentation::windows::WindowsCallbackService::InvokeGlobalTimer() 行 49	C++
 	MyGacUiTest.exe!vl::presentation::windows::WindowsController::InvokeGlobalTimer() 行 1943	C++
 	MyGacUiTest.exe!vl::presentation::windows::GodProc(HWND__ * hwnd, unsigned int uMsg, unsigned __int64 wParam, __int64 lParam) 行 1978	C++
 	[外部代码]	
 	MyGacUiTest.exe!vl::presentation::windows::WindowsController::Run(vl::presentation::INativeWindow * window) 行 1863	C++
 	MyGacUiTest.exe!vl::presentation::controls::GuiApplication::Run(vl::presentation::controls::GuiWindow * _mainWindow) 行 124	C++
 	MyGacUiTest.exe!GuiMain() 行 16	C++
 	MyGacUiTest.exe!vl::presentation::controls::GuiApplicationInitialize() 行 477	C++
 	MyGacUiTest.exe!GuiApplicationMain() 行 497	C++
 	MyGacUiTest.exe!RendererMainDirect2D() 行 781	C++
 	MyGacUiTest.exe!WinMainDirect2D(HINSTANCE__ * hInstance, void(*)() RendererMain) 行 629	C++
 	MyGacUiTest.exe!SetupWindowsDirect2DRenderer() 行 644	C++
 	MyGacUiTest.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int CmdShow) 行 31	C++
 	[外部代码]

**Comment by bizehao** [comment]
[https://github.com/vczh-libraries/Release/tree/master/Tutorial/GacUI_Controls/Animation](url)  这个的几个小球转动的界面很容易触发

**Comment by bizehao** [comment]
和#3 的现象一样

**Comment by vczh** [comment]
我估摸着这是Direct2D的问题，在Windows 10的第一版及所有旧版Windows都不要用Direct2D的64位。我先close了，有什么新发现的话再reopen。

**Comment by bizehao** [comment]
我刚刚加了些修改,不会崩了，下面是我的修改

```cpp
#define IMPLEMENT_BRUSH_ELEMENT_RENDERER_LINEAR_GRADIENT_BRUSH(TRENDERER)\
			void TRENDERER::CreateBrush(IWindowsDirect2DRenderTarget* _renderTarget)\
			{\
				if(_renderTarget)\
				{\
					oldColor=Pair<Color, Color>(element->GetColor1(), element->GetColor2());\
					brush=_renderTarget->CreateDirect2DLinearBrush(oldColor.key, oldColor.value);\
					brush->AddRef();\ //新增
				}\
			}\
			void TRENDERER::DestroyBrush(IWindowsDirect2DRenderTarget* _renderTarget)\
			{\
				if(_renderTarget && brush)\
				{\
					_renderTarget->DestroyDirect2DLinearBrush(oldColor.key, oldColor.value);\
					brush->Release(); \ //新增
					brush = nullptr; \ //新增 可有可无
				}\
			}\
```

**Comment by vczh** [comment]
这就很奇怪，CreateDirect2DLinearBrush内部就是保证refcount是1的，而且也没人Release过（除了render target没了之后释放全部东西），理应不需要这么修改。不过如果这样确实能解决问题那我就加上去。
