### ISSUE TITLE
Window ClientSize 还能缩小一些

### ISSUE THREAD

**Issue by bizehao** [vczh-libraries/GacUI#77]
```
<Window ref.Name="self" Text="GacUI XML资源展示" ClientSize="x:740 y:480">
        <att.BoundsComposition-set PreferredMinSize="x:740 y:480" />
</Window>
```
还能缩小大概20像素吧 按理说启动后的就是最小大小了吧

**Comment by vczh** [comment]
你试试这样干？
```XML
<Bounds <!-- 放一个Bounds而不是修改BoundsComposition -->
   PreferredMinSize="x:740 y:480"
   AlignmentToParent="left:0 top:0 right:0 bottom:0" <!-- 得添加这个，不然不能约束Window -->
    />
```

**Comment by bizehao** [comment]
我看了代码，感觉像是拉伸变化判断的最小大小没有进行dpi的处理

这是我做了下修改,可以达到我想的那种

![QQ截图20220615232004](https://user-images.githubusercontent.com/33247680/173864557-57de314a-7a95-4934-915e-520c60183310.png)

**Comment by vczh** [comment]
我这几天来看看。NativeRect是DPI有关坐标，而composition一套出来的是DPI无关坐标，我看看怎么做比较好，毕竟如果Windows平台有这个问题的话，其他平台也会有这样的问题。

**Comment by bizehao** [comment]
好的👌

**Comment by vczh** [comment]
一开始我没有仔细看，后来发现你应该设置的是 `<att.ContainerComposition-set PreferredMinSize="x:640 y:480/>`，因为`BoundsComposition`其实是窗口最外面的那一层，他有边框，所以客户区的确会比他更小一点。你看看是不是这样？

**Comment by bizehao** [comment]
但是我把里面走了dpi处理后，就符合预期了。主要就是能限制窗口的最小缩放大小就行

**Comment by vczh** [comment]
> 但是我把里面走了dpi处理后

但是`BoundsComposition`确实不能那么用（

**Comment by bizehao** [comment]
所以这块采用什么方式好一些

**Comment by vczh** [comment]
默认的皮肤都会保证自带以下效果
`<att.ContainerComposition-set MinSizeLimitation="LimitToElementAndChildren"/>`
所以通常情况下只要放进控件里面的东西有一个最小值就好了，不过你这种情况下直接写
```
<Window>
<att.ContainerComposition-set PreferredMinSize="..."/>
</Window>
```
也没关系，当然还有另一种比较麻烦的写法
```
<Window>
  <Bounds AlignmentToParent="left:0 top:0 right:0 bottom:0 PreferredMinSize="...">
    <!-- 东西放在这里面 -->
  </Bounds>
</Window>
```

`att.BoundsComposition` 一般只推荐修改哪些约束自己跟parent的关系的属性（譬如AlignmentToParent就是其中之一），而且`Window`的`att.BoundsComposition`代表的是窗口最外面那一圈（换了个皮肤说不定会变，不过默认的是这样），你约束那里的大小，client area自然会更小一点，因为要去掉边框。不知道你那个修改是不是巧合。

**Comment by bizehao** [comment]
我是按照你的示例这么写的。不是巧合，你可以改成我加的那个试试，就是不太优雅。

**Comment by vczh** [comment]
`att.BoundsComposition-set`设置的尺寸在这个皮肤上是针对window边框的，然后你用`AdjustWindowRect`把对window area的要求转移到了client area上面，但是`AdjustWindowRect`又怎么知道我的皮肤的client area应该是多大呢。实际上是`INativeWindow`提供了`GetCustomFramePadding`，然后我一步一步把他绑定到了我的皮肤上，所以client area恰好跟`AdjustWindowRect`效果一样了。

所以其实还是应该修改`att.ContainerComposition`。

不过看你这么一说，我去看了我的tutorial，好像还真的是我的tutorial写错了，下次升级的时候我把它们改了🤪

**Comment by bizehao** [comment]
用att.ContainerComposition的话会抖动，你这边呢

**Comment by vczh** [comment]
抖动修了，你可以试试。发现犯了一个傻逼错误，你看看代码就知道了 XD

**Comment by bizehao** [comment]
好的，下班回去了试下

**Comment by bizehao** [comment]
抱歉 出差了一周多

我更新成你的试了下 之前的问题没了 想问一个问题
就是 
在 ```<Window ref.Name="self" Text="GacUI XML资源临时测试" ClientSize="...">```下

<att.BoundsComposition-set PreferredMinSize="..." />限制的是整个窗口包括标题栏的大小
<att.ContainerComposition-set PreferredMinSize="..."/>限制的是除去标题栏后的内容窗口的大小

是这样吗

**Comment by vczh** [comment]
`ContainerComposition`限制的肯定是内容的大小，但是`BoundsComposition`是跟皮肤的实现有关的，在默认的实现里面限制的是外圈的大小。既然你也没看到问题那我就close了。
