### ISSUE TITLE
x64下崩溃问题的原因找到了

### ISSUE THREAD

**Issue by bizehao** [vczh-libraries/GacUI#78]
轮子哥，在GuiTypes.h里的Color的
```
vint Compare(Color color)const
{
	return value - color.value;
}
```
这个永远是大于0的数,导致比较运算符的结果不正确，我在vs下做的测试
```
        vuint32_t a = 100;
	vuint32_t b = 800;
	vint c = a - b; //4294966596
	vint d = b - a;//700
```
这里value是vuint32_t，应该把value换成vint32_t

应该是这里的比较运算导致的map取值问题，进而导致资源获取的问题， 我改成这个后  就正常了。上次改的那个应该是延长了brush的生存周期，现在撤销掉也正常了 ，回退成你之前的了。

**Comment by vczh** [comment]
怪了，那为啥同一个程序我已经好几年没看到崩溃了，如果是这种问题应该稳定崩溃才对。

**Comment by bizehao** [comment]
在DEFINE_CACHED_RESOURCE_ALLOCATOR这个宏的实现里, 我估计是你的Dictionary实现的问题，因为我替换成std::map的话,这个Color作为key触发的就很明显,不过是另一种现象了,然后我追代码,发现这个比较运算一直计算为true,换个key就好了,再切成你的Dictionary  也正常了,再把Color的比较运算符还原，问题又出现了。

用 [https://github.com/vczh-libraries/Release/tree/master/Tutorial/GacUI_Controls/Animation](https://github.com/vczh-libraries/GacUI/issues/url) 这个例子才行，其他的确实不容易触发,这个动画里这个好多颜色相同公用资源，然后一直取啥的,容易触发

**Comment by vczh** [comment]
虽然我还是不能repro，不过我还是这么改了吧，说不定是因为我升级了电脑导致没办法repro的 XD
