### ISSUE TITLE
界面缩放异常

### ISSUE THREAD

**Issue by eo0yuanhao** [vczh-libraries/GacUI#82]
我下载了代码，直接跑Tutorial\GacUI_Xml\Binding_Uri这个例子时，发现在缩放窗口高度时点小问题。在边框下面拖动缩小的时候，它会缩小一点，到一定大小后，又会还原回去，有点问题还能接受。不过在边框上面拖动缩小的时候，整个界面会抖动起来，然后整个窗口都会向下移动一段距离。

**Comment by vczh** [comment]
自己关了的话那我假设没这个问题？我记得几个月前修过的，不过没出新版本的release我记得。
