### ISSUE TITLE
合成规则

### ISSUE THREAD

**Issue by car520120** [vczh-libraries/GacUI#83]
能不能把合成规则写一下给我的呀？
我想使用 xmake 写一下这个工程，因为 xmake 可以使用IO功能合成文件的
也是支持跨平台的

**Comment by vczh** [comment]
我有makefile的，你可以去看看。

https://github.com/vczh-libraries/GacUI/tree/master/Test/Linux

**Comment by car520120** [comment]
其实是因为你 release 的代码是由多个cpp 组合成一个的，我想知道的是这个规则，你的头文件也是一样由多个合并成一个的

**Comment by vczh** [comment]
你直接用合并后的文件不就好了，都在[release repo](https://github.com/vczh-libraries/Release/tree/master/Import)里面。

我之所以这样做，是因为各个repo的开发进度是不一样的，只有当互相之间编译测试完了才会搬进release repo一次。所以你不应该直接访问合并前的文件，多半是过不了编译的。
