### ISSUE TITLE
failed to run GacBuild.ps1 against a commented Resource.xml

### ISSUE THREAD

**Issue by jamesboltn** [vczh-libraries/GacUI#86]
With release 1.0-rc-3，if  I try to GacBuild a resouce.xml with single commented line like this:
![image](https://user-images.githubusercontent.com/25360844/200092110-0a3acf5a-8e3b-4e30-b6ac-f33a50378120.png)

I got following output error:
![image](https://user-images.githubusercontent.com/25360844/200092170-20d091ce-07bf-4c17-bac2-5b742a9de527.png)

**Comment by vczh** [comment]
It doesn't crash in the latest version, it could due to that the XML parser got replaced after `1.0-rc-3`.
