### ISSUE TITLE
制作自己额外的控件

### ISSUE THREAD

**Issue by bizehao** [vczh-libraries/GacUI#87]
我目前想使用自己的一些控件,是直接在源码中添加,在GuiReflectionPlugin.h里注册 ,然后生成新的Reflection64.bin,才能通过GacGen把对应的xml元素解析成对应的控件.

请问下 可以通过外部方式来吗

**Comment by vczh** [comment]
如果不用GacGen来生成新的Reflection64.bin，你用这些控件的时候，XML怎么会知道哪个类里面有什么东西呢？这是目前最简单的办法。

**Comment by bizehao** [comment]
ok，明白
