### ISSUE TITLE
不支持windows10?

### ISSUE THREAD

**Issue by zmyspc** [vczh-libraries/GacUI#9]
弄了半天发现win10下运行编译好的几个exe毫无反映,似乎是还没有支持win10?

**Comment by vczh** [comment]
家里还没装Win10没运行过，你用Visual Studio调试一下是怎么回事？

**Comment by zmyspc** [comment]
GacUI\Import\Vlpp.h
#if defined VCZH_MSVC
					vint32_t count = -1;
					reader << count;
					collections::Array<wchar_t> buffer(count + 1);
					if (reader.input.Read((void*)&buffer[0], count*sizeof(wchar_t)) != count*sizeof(wchar_t))
					{
						CHECK_FAIL(L"Deserialization failed.");//这里失败了
					}
					buffer[count] = 0;

**Comment by zmyspc** [comment]
win10编译出的exe拿到win7虚拟机上也停止运行,
故障模块名称:	MSVCR120.dll

**Comment by vczh** [comment]
@zmyspc VerifyVersionInfo在GacUI里面只用来确定缺省使用的皮肤，所以其实并没有什么关系，最多在Win7下面跑出了Win8的皮肤。关于MSVCR120.dll的问题，要不你试试静态链接？我觉得不太可能因为我的代码导致MSVCR120.dll出问题吧？

**Comment by mat0thew** [comment]
**GacUISrc.exe** on **Windows 10** (*Visual Studio 2013*) compiled successful. But during start the program interrupts work and **crushed**.

**Comment by vczh** [comment]
@mat0thew You are not supposed to use the GacUISrc project, this is for my development only. What you are expected to compile are all tutorials in the repo called "Release". You can contact me if you have any trouble.

**Comment by lxj0276** [comment]
@vczh lunzi brother ,ni de english zheme diaobao,shi zen me study de a ?

**Comment by cxx909221500** [comment]
@lxj0276 Hello,ni de english also diaobao,lunzi brother had been living in Ricecountry(i cai de (≧０≦).)
And i thought my english ye bu worry

**Comment by joshuafc** [comment]
@lxj0276 @cxx909221500 , ni men de English really diaobaole.  And i thought my english ye bu error.

**Comment by lxj0276** [comment]
@joshuafc 1 error 5 warning

**Comment by vczh** [comment]
经过长时间在Windows 10的开发我没发现什么问题，故close。
